<?php

namespace Datawalke\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRevsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRevsRepository extends EntityRepository
{
}
